version: '3.4'

services:
  seq:
    image: datalust/seq:latest

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest

  pgsql-server:
    image: postgres:15

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity-api:
    image: ${DOCKER_REGISTRY-}identity.api
    build:
      context: .
      dockerfile: Services/IdentityUser/Identity.API/Dockerfile
    depends_on:
      - mssql-server
      - seq

  usermanagement-api:
    image: ${DOCKER_REGISTRY-}usermanagement.api
    build:
      context: .
      dockerfile: Services/IdentityUser/UserManagement.API/Dockerfile
    depends_on:
      - mssql-server
      - identity-api
      - seq
      - rabbitmq

  dictionary-api:
    image: ${DOCKER_REGISTRY-}dictionary.api
    build:
      context: .
      dockerfile: Services/Dictionary/Dictionary.API/Dockerfile
    depends_on:
      - pgsql-server
      - identity-api
      - seq

  testing-api:
    image: ${DOCKER_REGISTRY-}testing.api
    build:
      context: .
      dockerfile: Services/Testing/Testing.API/Dockerfile
    depends_on:
      - pgsql-server
      - identity-api
      - seq
      - rabbitmq

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile
    depends_on:
      - identity-api
      - usermanagement-api
      - dictionary-api
      - testing-api

  webspa:
    image: ${DOCKER_REGISTRY-}webspa
    build:
      context: .
      dockerfile: Web Apps/WebSPA/Dockerfile
    depends_on:
      - ocelotapigw

  webstatus:
    image: ${DOCKER_REGISTRY-}webstatus
    build:
      context: .
      dockerfile: Web Apps/WebStatus/Dockerfile
    depends_on:
      - webspa