version: '3.4'

services:
  sql-server:
    environment:
        SA_PASSWORD: SwN12345678
        ACCEPT_EULA: Y
    restart: always
    ports:
        - 1433:1433
    volumes:
      - sql-server-data:/var/opt/mssql

  pgsql-server:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - '5432:5432'
    volumes: 
      - pgsql-server-data:/var/lib/postgresql/data

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql-server;Database=Services.IdentityDb;User Id=sa;Password=SwN12345678;Trust Server Certificate=true;
    ports:
      - 8000:80

  usermanagement-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql-server;Database=Services.IdentityDb;User Id=sa;Password=SwN12345678;Trust Server Certificate=true;
      - IdentityUrl=http://identity-api
    ports:
      - 8001:80

  dictionary-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Host=pgsql-server;Port=5432;Database=Services.DictionaryDb;Username=postgres;Password=postgres;
      - IdentityUrl=http://identity-api
    ports:
      - 8002:80

volumes:
  sql-server-data:
  pgsql-server-data: