version: '3.4'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest

  identity-api:
    image: ${DOCKER_REGISTRY-}identity.api
    build:
      context: .
      dockerfile: Services/IdentityUser/Identity.API/Dockerfile
    depends_on:
      - sql-server

  usermanagement-api:
    image: ${DOCKER_REGISTRY-}usermanagement.api
    build:
      context: .
      dockerfile: Services/IdentityUser/UserManagement.API/Dockerfile
    depends_on:
      - sql-server
      - identity-api

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile
    depends_on:
      - identity-api
      - usermanagement-api