version: '3.4'

services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 7000:80

  mssql-server:
    environment:
        SA_PASSWORD: SwN12345678
        ACCEPT_EULA: Y
    restart: always
    ports:
        - 1433:1433
    volumes:
      - mssql-server-data:/var/opt/mssql

  pgsql-server:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - '5432:5432'
    volumes: 
      - pgsql-server-data:/var/lib/postgresql/data

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=mssql-server;Database=Services.IdentityDb;User Id=sa;Password=SwN12345678;Trust Server Certificate=true;
      - UserManagementApiClient=http://localhost:8001
      - DictionaryApiClient=http://localhost:8002
      - SpaClient=http://localhost:8011
      - SeqServerUrl=http://seq
    ports:
      - 8000:80

  usermanagement-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=mssql-server;Database=Services.IdentityDb;User Id=sa;Password=SwN12345678;Trust Server Certificate=true;
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://localhost:8000
      - SeqServerUrl=http://seq
    ports:
      - 8001:80

  dictionary-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Host=pgsql-server;Port=5432;Database=Services.DictionaryDb;Username=postgres;Password=postgres;
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://localhost:8000
      - SeqServerUrl=http://seq
    ports:
      - 8002:80

  ocelotapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity-api
      - SeqServerUrl=http://seq
    ports:
      - 8010:80

  webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity-api
      - IdentityUrlExternal=http://localhost:8000
      - Ocelotapigw=http://ocelotapigw
      - IdentityUrlHC=http://identity-api/hc
      - SeqServerUrl=http://seq
    ports:
      - 8011:80

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HealthChecksUI__HealthChecks__0__Name=Identity HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://identity-api/hc
      - HealthChecksUI__HealthChecks__1__Name=UserManagement HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://usermanagement-api/hc
      - HealthChecksUI__HealthChecks__2__Name=WebSPA HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://webspa/hc
      - SeqServerUrl=http://seq
    ports:
      - 8012:80

volumes:
  mssql-server-data:
  pgsql-server-data: