version: '3.4'

services:
  identitydb:
    container_name: identitydb
    user: root
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql/data

  identity.api:
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"
