version: '3.4'

services:
  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

volumes:
  sqlserver_data: