version: '3.4'

services:
  sql-server:
    user: root
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
    volumes:
      - sql-server-data:/var/opt/mssql/data

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql-server;Database=Services.IdentityDb;User Id=sa;Password=SwN12345678;TrustServerCertificate=True;MultiSubnetFailover=True;
    ports:
      - "8000:80"

volumes:
  sql-server-data: